export const resourceOrder = [
  'empresas',
  'contactos',
  'contratos_empresa',
  'lineas',
  'casos',
  'documentos',
  'categorias',
  'tipo_contactos',
  'estado_contactos',
  'estado_vitales',
  'estados_ctr',
  'tipo_servicios',
  'tipo_tarifas',
  'frecuencias',
]

export const auditFields = [
  { name: 'usuario_creacion', label: 'Creado por', type: 'text', readOnly: true },
  { name: 'fecha_creacion', label: 'Fecha creacion', type: 'datetime-local', readOnly: true },
  {
    name: 'fecha_actualizacion',
    label: 'Ultima actualizacion',
    type: 'datetime-local',
    readOnly: true,
  },
]

export const resources = {
  empresas: {
    title: 'Empresas',
    singular: 'Empresa',
    endpoint: 'empresas',
    idField: 'rut',
    defaultSort: 'rut',
    required: ['rut', 'razon_social', 'id_categoria'],
    listFields: ['rut', 'razon_social', 'nombre_fantasia', 'rubro', 'categoria'],
    formSections: [
      {
        title: 'Identificacion',
        icon: 'building',
        fields: ['rut', 'id_categoria', 'razon_social', 'nombre_fantasia'],
      },
      { title: 'Clasificacion', icon: 'industry', fields: ['giro', 'rubro', 'sitio_web'] },
      { title: 'Ubicacion', icon: 'map', fields: ['direccion', 'region', 'ciudad', 'comuna'] },
    ],
    fields: [
      { name: 'rut', label: 'RUT empresa', type: 'chile-rut', required: true },
      { name: 'razon_social', label: 'Razon social', type: 'text', required: true },
      { name: 'nombre_fantasia', label: 'Nombre fantasia', type: 'text' },
      { name: 'giro', label: 'Giro', type: 'text' },
      { name: 'rubro', label: 'Rubro', type: 'text' },
      {
        name: 'id_categoria',
        label: 'Categoria',
        type: 'select',
        lookup: 'categorias',
        required: true,
      },
      { name: 'direccion', label: 'Direccion', type: 'text' },
      { name: 'region', label: 'Region', type: 'chile-region' },
      { name: 'ciudad', label: 'Ciudad', type: 'chile-city', dependsOn: 'region' },
      { name: 'comuna', label: 'Comuna', type: 'chile-comuna', dependsOn: 'ciudad' },
      { name: 'sitio_web', label: 'Sitio web', type: 'text' },
    ],
  },
  contactos: {
    title: 'Contactos',
    singular: 'Contacto',
    endpoint: 'contactos',
    idField: 'id_contacto',
    defaultSort: 'id_contacto',
    required: ['id_tipo_contacto', 'id_estado_contacto', 'nombre'],
    listFields: ['id_contacto', 'nombre', 'empresa', 'tipo_contacto', 'estado_contacto', 'email'],
    formSections: [
      {
        title: 'Tipo y estado',
        icon: 'building',
        fields: ['id_tipo_contacto', 'id_estado_contacto'],
      },
      {
        title: 'Datos del contacto',
        icon: 'contact',
        fields: ['nombre', 'rut', 'cargo', 'area', 'rol'],
      },
      {
        title: 'Comunicacion',
        icon: 'phone',
        fields: ['email', 'telefono', 'autoriza_comunicaciones'],
      },
    ],
    fields: [
      {
        name: 'id_tipo_contacto',
        label: 'Tipo contacto',
        type: 'select',
        lookup: 'tipo_contactos',
        required: true,
      },
      {
        name: 'id_estado_contacto',
        label: 'Estado contacto',
        type: 'select',
        lookup: 'estado_contactos',
        required: true,
      },
      { name: 'rut', label: 'RUT contacto', type: 'chile-rut' },
      { name: 'nombre', label: 'Nombre', type: 'text', required: true },
      { name: 'cargo', label: 'Cargo', type: 'text' },
      { name: 'area', label: 'Area', type: 'text' },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'telefono', label: 'Telefono', type: 'text' },
      { name: 'rol', label: 'Rol', type: 'text' },
      { name: 'autoriza_comunicaciones', label: 'Autoriza comunicaciones', type: 'boolean' },
    ],
  },
  contratos_empresa: {
    title: 'Contratos Empresa',
    singular: 'Contrato Empresa',
    endpoint: 'contratos_empresa',
    idField: 'id',
    defaultSort: 'id',
    audit: false,
    required: [
      'rut_empresa',
      'id_categoria',
      'id_tipo_servicio',
      'id_estado_vital',
      'id_estado_ctr',
      'titulo',
      'id_frecuencia',
      'id_tipo_tarifa',
      'id_contacto',
      'id_tipo_contacto',
      'id_estado_contacto',
    ],
    listFields: [
      'codigo_contrato_empresa',
      'titulo',
      'empresa',
      'estado_ctr',
      'estado_vital',
      'fecha_inicio',
    ],
    formSections: [
      {
        title: 'Empresa y contrato',
        icon: 'briefcase',
        fields: ['codigo_contrato_empresa', 'rut_empresa', 'id_categoria', 'titulo'],
      },
      {
        title: 'Estados y servicio',
        icon: 'task',
        fields: ['id_tipo_servicio', 'id_estado_vital', 'id_estado_ctr'],
      },
      {
        title: 'Fechas y facturacion',
        icon: 'calendar',
        fields: [
          'fecha_firma',
          'fecha_inicio',
          'fecha_termino',
          'fecha_facturacion',
          'id_frecuencia',
          'id_tipo_tarifa',
        ],
      },
      {
        title: 'Condiciones',
        icon: 'money',
        fields: ['medio_pago', 'reajustable', 'multa', 'requiere_orden_compra'],
      },
      {
        title: 'Contacto',
        icon: 'contact',
        fields: ['id_contacto', 'id_tipo_contacto', 'id_estado_contacto'],
      },
    ],
    fields: [
      {
        name: 'codigo_contrato_empresa',
        label: 'Codigo contrato',
        type: 'text',
        readOnly: true,
      },
      { name: 'rut_empresa', label: 'Empresa', type: 'select', lookup: 'empresas', required: true },
      {
        name: 'id_categoria',
        label: 'Categoria',
        type: 'select',
        lookup: 'categorias',
        required: true,
      },
      {
        name: 'id_tipo_servicio',
        label: 'Tipo servicio',
        type: 'select',
        lookup: 'tipo_servicios',
        required: true,
      },
      {
        name: 'id_estado_vital',
        label: 'Estado vital',
        type: 'select',
        lookup: 'estado_vitales',
        required: true,
      },
      {
        name: 'id_estado_ctr',
        label: 'Estado contrato',
        type: 'select',
        lookup: 'estados_ctr',
        required: true,
      },
      { name: 'titulo', label: 'Titulo', type: 'text', required: true },
      { name: 'fecha_firma', label: 'Fecha firma', type: 'date' },
      { name: 'fecha_inicio', label: 'Fecha inicio', type: 'date' },
      { name: 'fecha_termino', label: 'Fecha termino', type: 'date' },
      { name: 'fecha_facturacion', label: 'Fecha facturacion', type: 'date' },
      { name: 'medio_pago', label: 'Medio pago', type: 'text' },
      { name: 'reajustable', label: 'Reajustable', type: 'boolean' },
      { name: 'multa', label: 'Multa', type: 'number' },
      { name: 'requiere_orden_compra', label: 'Requiere orden compra', type: 'boolean' },
      {
        name: 'id_frecuencia',
        label: 'Frecuencia',
        type: 'select',
        lookup: 'frecuencias',
        required: true,
      },
      {
        name: 'id_tipo_tarifa',
        label: 'Tipo tarifa',
        type: 'select',
        lookup: 'tipo_tarifas',
        required: true,
      },
      {
        name: 'id_contacto',
        label: 'Contacto',
        type: 'select',
        lookup: 'contactos',
        required: true,
      },
      {
        name: 'id_tipo_contacto',
        label: 'Tipo contacto',
        type: 'select',
        lookup: 'tipo_contactos',
        required: true,
      },
      {
        name: 'id_estado_contacto',
        label: 'Estado contacto',
        type: 'select',
        lookup: 'estado_contactos',
        required: true,
      },
      { name: 'created_at', label: 'Fecha creacion sistema', type: 'datetime-local', readOnly: true },
      {
        name: 'updated_at',
        label: 'Fecha actualizacion sistema',
        type: 'datetime-local',
        readOnly: true,
      },
    ],
  },
  lineas: {
    title: 'Lineas de contrato',
    singular: 'Linea',
    endpoint: 'lineas',
    idField: 'id_linea',
    defaultSort: 'id_linea',
    required: ['contrato_empresa_id', 'id_tipo_servicio', 'id_tipo_tarifa', 'id_frecuencia', 'titulo'],
    listFields: [
      'id_linea',
      'titulo',
      'contrato',
      'tipo_servicio',
      'tipo_tarifa',
      'frecuencia',
      'divisa',
      'tarifa_fija',
      'tarifa_variable',
    ],
    formSections: [
      {
        title: 'Contrato y servicio',
        icon: 'list',
        fields: ['contrato_empresa_id', 'titulo', 'id_tipo_servicio', 'id_tipo_tarifa', 'id_frecuencia'],
      },
      {
        title: 'Ciclo de facturacion',
        icon: 'calendar',
        fields: ['fecha_inicio', 'fecha_inicio_ciclo_facturacion'],
      },
      {
        title: 'Tarifas',
        icon: 'money',
        fields: [
          'divisa',
          'tarifa_fija',
          'moneda_fijo',
          'tarifa_variable',
          'moneda_variable',
          'unidad_variable',
          'iva',
        ],
      },
    ],
    fields: [
      {
        name: 'contrato_empresa_id',
        label: 'Contrato empresa',
        type: 'select',
        lookup: 'contratos_empresa_lookup',
        required: true,
      },
      {
        name: 'id_tipo_servicio',
        label: 'Tipo servicio',
        type: 'select',
        lookup: 'tipo_servicios',
        required: true,
      },
      {
        name: 'id_tipo_tarifa',
        label: 'Tipo tarifa',
        type: 'select',
        lookup: 'tipo_tarifas',
        required: true,
      },
      {
        name: 'id_frecuencia',
        label: 'Frecuencia',
        type: 'select',
        lookup: 'frecuencias',
        required: true,
      },
      { name: 'titulo', label: 'Titulo', type: 'text', required: true },
      { name: 'fecha_inicio', label: 'Fecha inicio', type: 'date' },
      { name: 'fecha_inicio_ciclo_facturacion', label: 'Inicio ciclo facturacion', type: 'date' },
      {
        name: 'divisa',
        label: 'Divisa',
        type: 'static-select',
        options: ['Peso', 'UF'],
        defaultValue: 'Peso',
      },
      { name: 'tarifa_fija', label: 'Tarifa fija', type: 'currency-amount' },
      { name: 'tarifa_variable', label: 'Tarifa variable', type: 'currency-amount' },
      { name: 'moneda_fijo', label: 'Moneda fijo', type: 'text' },
      { name: 'moneda_variable', label: 'Moneda variable', type: 'text' },
      { name: 'unidad_variable', label: 'Unidad variable', type: 'text' },
      { name: 'iva', label: 'IVA', type: 'boolean', defaultValue: true },
    ],
  },
  casos: {
    title: 'Casos',
    singular: 'Caso',
    endpoint: 'casos',
    idField: 'id_caso',
    defaultSort: 'id_caso',
    required: ['id_contacto', 'contrato_empresa_id', 'titulo'],
    listFields: ['id_caso', 'titulo', 'contacto', 'contrato', 'adjuntos'],
    formSections: [
      {
        title: 'Relacion',
        icon: 'contact',
        fields: ['id_contacto', 'contrato_empresa_id', 'titulo'],
      },
      { title: 'Detalle del caso', icon: 'notes', fields: ['texto', 'relato', 'adjuntos'] },
    ],
    fields: [
      {
        name: 'id_contacto',
        label: 'Contacto',
        type: 'select',
        lookup: 'contactos',
        required: true,
      },
      {
        name: 'contrato_empresa_id',
        label: 'Contrato empresa',
        type: 'select',
        lookup: 'contratos_empresa_lookup',
        required: true,
      },
      { name: 'titulo', label: 'Titulo', type: 'text', required: true },
      { name: 'texto', label: 'Texto', type: 'textarea' },
      { name: 'adjuntos', label: 'Archivo', type: 'file-upload' },
      { name: 'relato', label: 'Relato', type: 'textarea' },
    ],
  },
  documentos: {
    title: 'Documentos',
    singular: 'Documento',
    endpoint: 'documentos',
    idField: 'id_documento',
    defaultSort: 'id_documento',
    required: ['contrato_empresa_id', 'nombre'],
    listFields: ['id_documento', 'nombre', 'contrato', 'tipo_documento', 'version', 'estado'],
    formSections: [
      {
        title: 'Documento',
        icon: 'file',
        fields: ['contrato_empresa_id', 'tipo_documento', 'nombre', 'version', 'estado'],
      },
      {
        title: 'Gestion',
        icon: 'folder',
        fields: ['responsable', 'descripcion', 'archivo', 'fecha_carga'],
      },
    ],
    fields: [
      {
        name: 'contrato_empresa_id',
        label: 'Contrato empresa',
        type: 'select',
        lookup: 'contratos_empresa_lookup',
        required: true,
      },
      { name: 'tipo_documento', label: 'Tipo documento', type: 'text' },
      { name: 'nombre', label: 'Nombre', type: 'text', required: true },
      { name: 'descripcion', label: 'Descripcion', type: 'textarea' },
      { name: 'version', label: 'Version', type: 'text' },
      { name: 'responsable', label: 'Responsable', type: 'text' },
      { name: 'archivo', label: 'Archivo', type: 'file-upload' },
      { name: 'estado', label: 'Estado', type: 'text' },
      { name: 'fecha_carga', label: 'Fecha carga', type: 'datetime-local', readOnly: true },
    ],
  },
  categorias: {
    title: 'Categorias',
    singular: 'Categoria',
    endpoint: 'categorias',
    idField: 'id_categoria',
    defaultSort: 'id_categoria',
    required: ['categoria'],
    listFields: ['id_categoria', 'categoria'],
    fields: [{ name: 'categoria', label: 'Categoria', type: 'text', required: true }],
  },
  tipo_contactos: {
    title: 'Tipos de contacto',
    singular: 'Tipo de contacto',
    endpoint: 'tipo_contactos',
    idField: 'id_tipo_contacto',
    defaultSort: 'id_tipo_contacto',
    required: ['tipo'],
    listFields: ['id_tipo_contacto', 'tipo'],
    fields: [{ name: 'tipo', label: 'Tipo', type: 'text', required: true }],
  },
  estado_contactos: {
    title: 'Estados de contacto',
    singular: 'Estado de contacto',
    endpoint: 'estado_contactos',
    idField: 'id_estado_contacto',
    defaultSort: 'id_estado_contacto',
    required: ['estado_contacto'],
    listFields: ['id_estado_contacto', 'estado_contacto'],
    fields: [{ name: 'estado_contacto', label: 'Estado contacto', type: 'text', required: true }],
  },
  estado_vitales: {
    title: 'Estados vitales',
    singular: 'Estado vital',
    endpoint: 'estado_vitales',
    idField: 'id_estado_vital',
    defaultSort: 'id_estado_vital',
    required: ['estado_vital'],
    listFields: ['id_estado_vital', 'estado_vital'],
    fields: [{ name: 'estado_vital', label: 'Estado vital', type: 'text', required: true }],
  },
  estados_ctr: {
    title: 'Estados de contrato',
    singular: 'Estado de contrato',
    endpoint: 'estados_ctr',
    idField: 'id_estado_ctr',
    defaultSort: 'id_estado_ctr',
    required: ['estado_ctr'],
    listFields: ['id_estado_ctr', 'estado_ctr'],
    fields: [{ name: 'estado_ctr', label: 'Estado contrato', type: 'text', required: true }],
  },
  tipo_servicios: {
    title: 'Tipos de servicio',
    singular: 'Tipo de servicio',
    endpoint: 'tipo_servicios',
    idField: 'id_tipo_servicio',
    defaultSort: 'id_tipo_servicio',
    required: ['tipo_servicio'],
    listFields: ['id_tipo_servicio', 'tipo_servicio'],
    fields: [{ name: 'tipo_servicio', label: 'Tipo servicio', type: 'text', required: true }],
  },
  tipo_tarifas: {
    title: 'Tipos de tarifa',
    singular: 'Tipo de tarifa',
    endpoint: 'tipo_tarifas',
    idField: 'id_tipo_tarifa',
    defaultSort: 'id_tipo_tarifa',
    required: ['tipo_tarifa'],
    listFields: ['id_tipo_tarifa', 'tipo_tarifa'],
    fields: [{ name: 'tipo_tarifa', label: 'Tipo tarifa', type: 'text', required: true }],
  },
  frecuencias: {
    title: 'Frecuencias de facturacion',
    singular: 'Frecuencia',
    endpoint: 'frecuencias',
    idField: 'id_frecuencia',
    defaultSort: 'id_frecuencia',
    required: ['frecuencia'],
    listFields: ['id_frecuencia', 'frecuencia'],
    fields: [{ name: 'frecuencia', label: 'Frecuencia', type: 'text', required: true }],
  },
}

export const getFieldLabel = (config, fieldName) => {
  const field = config.fields.find((item) => item.name === fieldName)
  if (field) return field.label
  const auditField = auditFields.find((item) => item.name === fieldName)
  if (auditField) return auditField.label
  return fieldName
}
