export const resourceOrder = [
  'empresas',
  'contactos',
  'contratos',
  'lineas',
  'casos',
  'documentos',
  'categorias',
  'tipo_contactos',
  'estado_contactos',
  'estado_vitales',
  'tipo_servicios',
  'tipo_tarifas',
  'frecuencias',
]

export const resources = {
  empresas: {
    title: 'Empresas',
    singular: 'Empresa',
    endpoint: 'empresas',
    idField: 'rut',
    defaultSort: 'rut',
    required: ['rut', 'razon_social', 'id_categoria'],
    listFields: ['rut', 'razon_social', 'nombre_fantasia', 'rubro', 'categoria'],
    fields: [
      { name: 'rut', label: 'RUT empresa', type: 'text', required: true, createOnly: true },
      { name: 'razon_social', label: 'Razon social', type: 'text', required: true },
      { name: 'nombre_fantasia', label: 'Nombre fantasia', type: 'text' },
      { name: 'giro', label: 'Giro', type: 'text' },
      { name: 'rubro', label: 'Rubro', type: 'text' },
      { name: 'direccion', label: 'Direccion', type: 'text' },
      { name: 'region', label: 'Region', type: 'chile-region' },
      { name: 'comuna', label: 'Comuna', type: 'chile-comuna', dependsOn: 'region' },
      { name: 'sitio_web', label: 'Sitio web', type: 'text' },
      {
        name: 'id_categoria',
        label: 'Categoria',
        type: 'select',
        lookup: 'categorias',
        required: true,
      },
    ],
  },
  contactos: {
    title: 'Contactos',
    singular: 'Contacto',
    endpoint: 'contactos',
    idField: 'id_contacto',
    defaultSort: 'id_contacto',
    required: ['rut_empresa', 'id_tipo_contacto', 'id_estado_contacto', 'nombre'],
    listFields: ['id_contacto', 'nombre', 'empresa', 'tipo_contacto', 'estado_contacto', 'email'],
    fields: [
      { name: 'rut_empresa', label: 'Empresa', type: 'select', lookup: 'empresas', required: true },
      {
        name: 'id_tipo_contacto',
        label: 'Tipo contacto',
        type: 'select',
        lookup: 'tipo_contactos',
        required: true,
      },
      {
        name: 'id_estado_contacto',
        label: 'Estado contacto',
        type: 'select',
        lookup: 'estado_contactos',
        required: true,
      },
      { name: 'rut', label: 'RUT contacto', type: 'text' },
      { name: 'nombre', label: 'Nombre', type: 'text', required: true },
      { name: 'cargo', label: 'Cargo', type: 'text' },
      { name: 'area', label: 'Area', type: 'text' },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'telefono', label: 'Telefono', type: 'text' },
      { name: 'rol', label: 'Rol', type: 'text' },
      { name: 'autoriza_comunicaciones', label: 'Autoriza comunicaciones', type: 'boolean' },
      { name: 'estado', label: 'Estado', type: 'text' },
    ],
  },
  contratos: {
    title: 'Contratos',
    singular: 'Contrato',
    endpoint: 'contratos',
    idField: 'id_contrato',
    defaultSort: 'id_contrato',
    required: ['rut_empresa', 'id_estado_vital', 'titulo'],
    listFields: [
      'id_contrato',
      'titulo',
      'empresa',
      'estado_vital',
      'fecha_inicio',
      'fecha_termino',
    ],
    fields: [
      { name: 'rut_empresa', label: 'Empresa', type: 'select', lookup: 'empresas', required: true },
      {
        name: 'id_estado_vital',
        label: 'Estado vital',
        type: 'select',
        lookup: 'estado_vitales',
        required: true,
      },
      { name: 'titulo', label: 'Titulo', type: 'text', required: true },
      { name: 'fecha_firma', label: 'Fecha firma', type: 'date' },
      { name: 'fecha_inicio', label: 'Fecha inicio', type: 'date' },
      { name: 'fecha_termino', label: 'Fecha termino', type: 'date' },
      { name: 'estado', label: 'Estado', type: 'text' },
      { name: 'fecha_facturacion', label: 'Fecha facturacion', type: 'date' },
      { name: 'medio_pago', label: 'Medio pago', type: 'text' },
      { name: 'reajustable', label: 'Reajustable', type: 'boolean' },
      { name: 'multa', label: 'Multa', type: 'number' },
      { name: 'requiere_oc', label: 'Requiere OC', type: 'boolean' },
    ],
  },
  lineas: {
    title: 'Lineas de contrato',
    singular: 'Linea',
    endpoint: 'lineas',
    idField: 'id_linea',
    defaultSort: 'id_linea',
    required: ['id_contrato', 'id_tipo_servicio', 'id_tipo_tarifa', 'id_frecuencia', 'titulo'],
    listFields: ['id_linea', 'titulo', 'contrato', 'tipo_servicio', 'tipo_tarifa', 'frecuencia'],
    fields: [
      {
        name: 'id_contrato',
        label: 'Contrato',
        type: 'select',
        lookup: 'contratos',
        required: true,
      },
      {
        name: 'id_tipo_servicio',
        label: 'Tipo servicio',
        type: 'select',
        lookup: 'tipo_servicios',
        required: true,
      },
      {
        name: 'id_tipo_tarifa',
        label: 'Tipo tarifa',
        type: 'select',
        lookup: 'tipo_tarifas',
        required: true,
      },
      {
        name: 'id_frecuencia',
        label: 'Frecuencia',
        type: 'select',
        lookup: 'frecuencias',
        required: true,
      },
      { name: 'titulo', label: 'Titulo', type: 'text', required: true },
      { name: 'fecha_inicio', label: 'Fecha inicio', type: 'date' },
      { name: 'fecha_inicio_ciclo_facturacion', label: 'Inicio ciclo facturacion', type: 'date' },
      { name: 'tarifa_fija', label: 'Tarifa fija', type: 'number' },
      { name: 'tarifa_variable', label: 'Tarifa variable', type: 'number' },
      { name: 'moneda_fijo', label: 'Moneda fijo', type: 'text' },
      { name: 'moneda_variable', label: 'Moneda variable', type: 'text' },
      { name: 'unidad_variable', label: 'Unidad variable', type: 'text' },
      { name: 'iva', label: 'IVA', type: 'boolean', defaultValue: true },
    ],
  },
  casos: {
    title: 'Casos',
    singular: 'Caso',
    endpoint: 'casos',
    idField: 'id_caso',
    defaultSort: 'id_caso',
    required: ['id_contacto', 'id_contrato', 'titulo'],
    listFields: ['id_caso', 'titulo', 'contacto', 'contrato'],
    fields: [
      {
        name: 'id_contacto',
        label: 'Contacto',
        type: 'select',
        lookup: 'contactos',
        required: true,
      },
      {
        name: 'id_contrato',
        label: 'Contrato',
        type: 'select',
        lookup: 'contratos',
        required: true,
      },
      { name: 'titulo', label: 'Titulo', type: 'text', required: true },
      { name: 'texto', label: 'Texto', type: 'textarea' },
      { name: 'adjuntos', label: 'Adjuntos', type: 'textarea' },
      { name: 'relato', label: 'Relato', type: 'textarea' },
    ],
  },
  documentos: {
    title: 'Documentos',
    singular: 'Documento',
    endpoint: 'documentos',
    idField: 'id_documento',
    defaultSort: 'id_documento',
    required: ['id_contrato', 'nombre'],
    listFields: ['id_documento', 'nombre', 'contrato', 'tipo_documento', 'version', 'estado'],
    fields: [
      {
        name: 'id_contrato',
        label: 'Contrato',
        type: 'select',
        lookup: 'contratos',
        required: true,
      },
      { name: 'tipo_documento', label: 'Tipo documento', type: 'text' },
      { name: 'nombre', label: 'Nombre', type: 'text', required: true },
      { name: 'descripcion', label: 'Descripcion', type: 'textarea' },
      { name: 'version', label: 'Version', type: 'text' },
      { name: 'responsable', label: 'Responsable', type: 'text' },
      { name: 'archivo', label: 'Archivo / URL', type: 'textarea' },
      { name: 'estado', label: 'Estado', type: 'text' },
      { name: 'fecha_carga', label: 'Fecha carga', type: 'datetime-local', readOnly: true },
    ],
  },
  categorias: {
    title: 'Categorias',
    singular: 'Categoria',
    endpoint: 'categorias',
    idField: 'id_categoria',
    defaultSort: 'id_categoria',
    required: ['categoria'],
    listFields: ['id_categoria', 'categoria'],
    fields: [{ name: 'categoria', label: 'Categoria', type: 'text', required: true }],
  },
  tipo_contactos: {
    title: 'Tipos de contacto',
    singular: 'Tipo de contacto',
    endpoint: 'tipo_contactos',
    idField: 'id_tipo_contacto',
    defaultSort: 'id_tipo_contacto',
    required: ['tipo'],
    listFields: ['id_tipo_contacto', 'tipo'],
    fields: [{ name: 'tipo', label: 'Tipo', type: 'text', required: true }],
  },
  estado_contactos: {
    title: 'Estados de contacto',
    singular: 'Estado de contacto',
    endpoint: 'estado_contactos',
    idField: 'id_estado_contacto',
    defaultSort: 'id_estado_contacto',
    required: ['estado_contacto'],
    listFields: ['id_estado_contacto', 'estado_contacto'],
    fields: [{ name: 'estado_contacto', label: 'Estado contacto', type: 'text', required: true }],
  },
  estado_vitales: {
    title: 'Estados vitales',
    singular: 'Estado vital',
    endpoint: 'estado_vitales',
    idField: 'id_estado_vital',
    defaultSort: 'id_estado_vital',
    required: ['estado_vital'],
    listFields: ['id_estado_vital', 'estado_vital'],
    fields: [{ name: 'estado_vital', label: 'Estado vital', type: 'text', required: true }],
  },
  tipo_servicios: {
    title: 'Tipos de servicio',
    singular: 'Tipo de servicio',
    endpoint: 'tipo_servicios',
    idField: 'id_tipo_servicio',
    defaultSort: 'id_tipo_servicio',
    required: ['tipo_servicio'],
    listFields: ['id_tipo_servicio', 'tipo_servicio'],
    fields: [{ name: 'tipo_servicio', label: 'Tipo servicio', type: 'text', required: true }],
  },
  tipo_tarifas: {
    title: 'Tipos de tarifa',
    singular: 'Tipo de tarifa',
    endpoint: 'tipo_tarifas',
    idField: 'id_tipo_tarifa',
    defaultSort: 'id_tipo_tarifa',
    required: ['tipo_tarifa'],
    listFields: ['id_tipo_tarifa', 'tipo_tarifa'],
    fields: [{ name: 'tipo_tarifa', label: 'Tipo tarifa', type: 'text', required: true }],
  },
  frecuencias: {
    title: 'Frecuencias de facturacion',
    singular: 'Frecuencia',
    endpoint: 'frecuencias',
    idField: 'id_frecuencia',
    defaultSort: 'id_frecuencia',
    required: ['frecuencia'],
    listFields: ['id_frecuencia', 'frecuencia'],
    fields: [{ name: 'frecuencia', label: 'Frecuencia', type: 'text', required: true }],
  },
}

export const getFieldLabel = (config, fieldName) => {
  const field = config.fields.find((item) => item.name === fieldName)
  if (field) return field.label
  return fieldName
}
