const permissionModules = [
  {
    moduleKey: 'dashboard.main',
    moduleName: 'Dashboard',
    moduleGroup: 'General',
    menuPath: '/dashboard',
    sortOrder: 10,
  },
  {
    moduleKey: 'commercial.empresas',
    moduleName: 'Empresas',
    moduleGroup: 'Gestion comercial',
    menuPath: '/commercial/empresas',
    sortOrder: 100,
  },
  {
    moduleKey: 'commercial.contactos',
    moduleName: 'Contactos',
    moduleGroup: 'Gestion comercial',
    menuPath: '/commercial/contactos',
    sortOrder: 110,
  },
  {
    moduleKey: 'commercial.contratos',
    moduleName: 'Contratos',
    moduleGroup: 'Gestion comercial',
    menuPath: '/commercial/contratos',
    sortOrder: 120,
  },
  {
    moduleKey: 'commercial.contratos_empresa',
    moduleName: 'Contrato Empresa',
    moduleGroup: 'Gestion comercial',
    menuPath: '/commercial/contratos-empresa',
    sortOrder: 125,
  },
  {
    moduleKey: 'commercial.lineas',
    moduleName: 'Lineas de contrato',
    moduleGroup: 'Gestion comercial',
    menuPath: '/commercial/lineas',
    sortOrder: 130,
  },
  {
    moduleKey: 'commercial.casos',
    moduleName: 'Casos',
    moduleGroup: 'Gestion comercial',
    menuPath: '/commercial/casos',
    sortOrder: 140,
  },
  {
    moduleKey: 'commercial.documentos',
    moduleName: 'Documentos',
    moduleGroup: 'Gestion comercial',
    menuPath: '/commercial/documentos',
    sortOrder: 150,
  },
  {
    moduleKey: 'commercial.categorias',
    moduleName: 'Categorias',
    moduleGroup: 'Tablas maestras comerciales',
    menuPath: '/commercial/categorias',
    sortOrder: 200,
  },
  {
    moduleKey: 'commercial.tipo_contactos',
    moduleName: 'Tipos de contacto',
    moduleGroup: 'Tablas maestras comerciales',
    menuPath: '/commercial/tipo_contactos',
    sortOrder: 210,
  },
  {
    moduleKey: 'commercial.estado_contactos',
    moduleName: 'Estados de contacto',
    moduleGroup: 'Tablas maestras comerciales',
    menuPath: '/commercial/estado_contactos',
    sortOrder: 220,
  },
  {
    moduleKey: 'commercial.estado_vitales',
    moduleName: 'Estados vitales',
    moduleGroup: 'Tablas maestras comerciales',
    menuPath: '/commercial/estado_vitales',
    sortOrder: 230,
  },
  {
    moduleKey: 'commercial.estados_ctr',
    moduleName: 'Estados de contrato',
    moduleGroup: 'Tablas maestras comerciales',
    menuPath: '/commercial/estados_ctr',
    sortOrder: 235,
  },
  {
    moduleKey: 'commercial.tipo_servicios',
    moduleName: 'Tipos de servicio',
    moduleGroup: 'Tablas maestras comerciales',
    menuPath: '/commercial/tipo_servicios',
    sortOrder: 240,
  },
  {
    moduleKey: 'commercial.tipo_tarifas',
    moduleName: 'Tipos de tarifa',
    moduleGroup: 'Tablas maestras comerciales',
    menuPath: '/commercial/tipo_tarifas',
    sortOrder: 250,
  },
  {
    moduleKey: 'commercial.frecuencias',
    moduleName: 'Frecuencias de facturacion',
    moduleGroup: 'Tablas maestras comerciales',
    menuPath: '/commercial/frecuencias',
    sortOrder: 260,
  },
  {
    moduleKey: 'admin.users',
    moduleName: 'Gestion de usuarios',
    moduleGroup: 'Usuarios y seguridad',
    menuPath: '/admin/users',
    sortOrder: 300,
  },
  {
    moduleKey: 'admin.roles',
    moduleName: 'Roles y permisos',
    moduleGroup: 'Usuarios y seguridad',
    menuPath: '/admin/roles',
    sortOrder: 310,
  },
  {
    moduleKey: 'admin.audit',
    moduleName: 'Auditoria',
    moduleGroup: 'Usuarios y seguridad',
    menuPath: '/admin/audit',
    sortOrder: 320,
  },
]

module.exports = { permissionModules }
